// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddJobButton: typeof import('./components/AddJobButton.vue')['default']
    AddJobForm: typeof import('./components/AddJobForm.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    JobsTable: typeof import('./components/JobsTable.vue')['default']
    LocaleDropdown: typeof import('./components/LocaleDropdown.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    README: typeof import('./components/README.md')['default']
    TimezoneDropdown: typeof import('./components/TimezoneDropdown.vue')['default']
  }
}

export { }
